"""
analysis_response.py
--------------------
Pydantic schema for the structured AI insight output.

This is both the contract enforced on the LLM response and the shape of
data stored in llm_cache and returned to the API caller.

The strict list-length constraints (exactly 3 items) are enforced at parse
time via Field min_length / max_length so that any malformed LLM response
is caught and retried before it reaches the database or the caller.
"""

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field


class PrioritizedAction(BaseModel):
    """
    A single recommended action for the analyst to take.

    priority        : Urgency rank — 1 (most urgent) to 3 (least urgent).
    title           : Short imperative label (≤ 60 chars recommended).
    rationale       : Why this action matters, grounded in the Findings data.
    expected_impact : Quantified outcome where the data supports it.
    confidence      : LLM's confidence in this recommendation (0.0–1.0).
    """

    priority: int
    title: str
    rationale: str
    expected_impact: str
    confidence: float


class AnalysisResponse(BaseModel):
    """
    Structured AI insight report for one (dataset, month) pair.

    Generated by the LLM from the compact Findings payload. Stored verbatim
    in llm_cache and insights tables and returned directly to API callers.

    Fields
    ------
    type               : Always "insight_batch" — used as a type discriminator
                         by future agent layers.
    title              : Concise descriptive title for the period (≤ 80 chars).
    summary_bullets    : Exactly 3 sentences covering revenue, churn, and growth.
    prioritized_actions: Exactly 3 actions sorted by urgency (priority 1 first).
    next_checks        : Exactly 3 follow-up data questions worth investigating.
    key_numbers        : 3–6 decision-relevant metrics with clear human labels.
                         Values are float or null (unavailable).
    assumptions        : All data_quality warnings plus any LLM assumptions.
    confidence         : Overall analysis confidence (0.0–1.0).
                         Lower when warnings are present or prior-month data
                         is absent.
    """

    type: Literal["insight_batch", "explanation", "forecast"] = "insight_batch"
    title: str
    summary_bullets: Annotated[list[str], Field(min_length=3, max_length=3)]
    prioritized_actions: Annotated[
        list[PrioritizedAction], Field(min_length=3, max_length=3)
    ]
    next_checks: Annotated[list[str], Field(min_length=3, max_length=3)]
    key_numbers: dict[str, Optional[float]] = Field(default_factory=dict)
    assumptions: list[str]
    confidence: float
